### PR TITLE
Update accordion-code.js

### PR DESCRIPTION
**Pull request by Sparta-9**

### CODE REVIEW

**Comment by Sparta-9** [comment]
add

**Comment by thehairy** [comment]
Good that you closed it, because it's useless.

**Comment by marcosvega91** [comment]
I think that is not good to say that. I think that the guy has not a lot experience on Github so your message I think is not really helpful for him.  I have made a lot of wrong PRs at the beginning. 

I appreciate his help 🤖 , so I'll say thank to @Sparta-9 

Regards
Marco

**Comment by thehairy** [comment]
No, its just spamming to get a price from Hacktober where you need to make x merged pull reguests.

**Comment by kentcdodds** [comment]
🤖 This is Hacktoberfest spam and will be automatically deleted.

If you feel this was in error, please comment.

**Pull request closed without merging**
